In [17]:
import numpy


In [47]:
# non-dimentional array
n = numpy.arange(18)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [48]:
# two-dimentional array
n.reshape(3, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [54]:
# three-dimentional array
n.reshape(3, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [59]:
new_array = numpy.asarray([[123, 12, 123, 12, 33], [], []])
new_array

C:\Users\USER10\AppData\Local\Temp/ipykernel_15928/2865347694.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  new_array = numpy.asarray([[123, 12, 123, 12, 33], [], []])


array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)