In [11]:
import cv2

In [ ]:
# 1. Creating arrays from images

In [9]:
# read image  in grayscale
img_gray = cv2.imread("./images/smallgray.png", 0)
img_gray


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
# read the image in rgb
img_rgb = cv2.imread("./images/smallgray.png", 1)
img_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
# 2. Creating images from numpy arrays

In [15]:
arr_to_img = cv2.imwrite("./images/new_img.png", img_gray)
arr_to_img


True

In [17]:
# Indexing, slicing, and iterating numpy arrays
img_arr = cv2.imread("./images/image_01.png", 0)
img_arr

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
# give me the last two items from the 2nd and the 3rd lists.
result = img_arr[1:, -2:]
result

array([[255, 147],
       [ 97, 182]], dtype=uint8)

In [25]:
# iterating over numpy arrays

# for loop
for i in img_arr:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [27]:
# iterate over array columns
for i in img_arr.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [29]:
# iterate value by value
for i in img_arr.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [ ]:
# stocking(combining) numpy arrays

# stack two or more numpy arrays horizontally
new_arr = cv2.h
